language: python

python:
  - "3.5"
  
env:
  - DJANGO=1.11.2
  
install:
  - pip install -q django==$DJANGO
  
script:
  - python hellosite/manage.py test
  
deploy:
  provider: heroku
  api_key:
    secure: "LclawE2C/5YKgUYXUdSzURrgEMuD3p/5f60V+FLMu/rJW4JMv8rTMYnutFJ6TixxqIVfhjKszOy2ooMdGGNyzKnV5CWuv4vkBnKdebYCkn4CoiOAioe9LhTOPoN6h9kgrmHswN5BawrXS1EQl4gU/Ztmy47n9UThg/Snps+Cd5l94WBt2XMtazg6rOXpMF4bfSBu4vgJGesBd/6aSADfnm/l4mQVESvlnSFfLs0STjn5naku0VgXlZF6DTsJHqVEYF+iOnT99M6L9dWTPasmHxUagRCR5SR/y56rwgV9RtJY7uoUr9hfCxHpXh0NTfhoNVQHepqMENJCnG+KMi30vYNO+LjRXwyF6YnqKYfru9wh9a8c8IPnZERMY7ePy+S9kpF994ZWyjXU/D1GOEoBwniAlAnY7YiK9Q6ICVYqrf6tjx/EilN6uPiBMH4Kdmb+P7oZwiOO4SVtP/b80BS8MiKGWNRrODzLCHqXxXXMxJn/7niawlpk1he1zEwTbp4zG85MBwAPnMu+tD0KXBeThQDc3EvayAlrfEHk/bUpVkUv4G/KALn4trR+1B22h8Lmw+2TjhvGXDj2dxEM4tKhqZPqUvHcqjj2YLFZrRiYmj9HfH2VoNspMMKK3KjvEjozrmpwSw5LElzzEK92YoyqieH/5yFSnCdAZA8q6C1V/FI="
  
notifications:
  email: false
