language: python
python:
- '3.5'

env:
- DJANGO=1.11.2

install:
- pip install -q django==$DJANGO

script:
- python hellosite/manage.py test

deploy:
  provider: heroku
  api_key:
    secure: u/6ct5y0ozgDrA8v3Qh3ogr6z89hI+FrlQ2w9cueQnMOWNO6xTqzriwTywtjQNIdhfW4mRWS9QSllolD00QPyogAIwwC4RGZbmwC0N8kpkfvS4SvXzoxf6kwGUe/QscSQPFayouRJRYJpLR0qerIHW8+ElgPMdOvNYjLDDcV9bTgohiFQBGic865O/fh2DDbkH4gNQhnAaJHhgGKz+bmDbxTCPnTOhQqiuDiNhgJjxcsotVLYof0YLWKzPt7W0IHBA6icNdGO3BiaiU+ldDTM2F1AJsdqOkqvzV7K2d5fWIYbCtxFGT5WEIINP7BQrNMN4HYlohYHQFsE2KyRTpU8qBRXE1aXYxpk8BXDNbljZMT3Mte6ghKuewP5MkQfU2fXStIR2mIvA36t8FVw/GnTDE1/A5EfUos73uIi1KvKbK7BmI5ne8K174Fh0tLlQ6aEN3N47poGgiFcl3kjx8cvUdQp6gh/D1iM1uENtNjBPdnkh6ZZRGL2knysrH1TJCRF4Xpq5PA2oi8ydu9xH4K2qkgmZ+J+2C7dPKQg7rvI3l13biHbDosmBTAnVE4k18f6/gHuhDw4VUvPUg7UKibAyYS8PZ5Lv7etWiefev55YqB9PsqUOHbV7pNwYxEO7MJnNXPeg3jmhGebjagDSov3m7QlxT7wVtmiFtiCGWnXJ4=
  app: DSDP_l1
  on:
    repo: vikhotin/DSDP_l1
    
notifications:
  email: false
